### ISSUE TITLE
[Bug]: bug error after install on 27.1.4

### ISSUE THREAD

**Issue by punkyard** [nextcloud/maps#1176] opened 2023-12-12 19:22 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

right after install on AiO 781, first launch - black screen

Impossible de charger les contacts:

<div id="nojavascript">
<div>
Cette application requiert JavaScript pour fonctionner correctement. Veuillez <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">activer JavaScript</a> et recharger la page. </div>
</div>

### Steps to reproduce

1. install
2. launch

### Expected behavior

show map where i am and contacts?

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

Fresh Nextcloud Maps install (never installed before)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Activity	2.19.0	Featured

Disable
Antivirus for files	5.4.0	

Disable
Auditing / Logging	1.17.0	Featured

Disable
Auto Groups	1.5.2	

Disable
Brute-force settings	2.7.0	Featured

Disable
Calendar	4.6.0	Featured

Disable
Circles	27.0.1	Featured

Disable
Client Push	0.6.5	

Disable
Collectives	2.9.2	

Disable
Comments	1.17.0	Featured

Disable
Configurable Share Links	4.2.0	

Disable
Contacts	5.5.0	Featured

Disable
Custom menu	3.11.2	

Disable
Dashboard	7.7.0	Featured

Disable
Deck	1.11.2	Featured

Disable
Default group quota	0.1.7	

Disable
Deleted files	1.17.0	Featured

Disable
External sites	5.2.1	Featured

Disable
File reminders	1.0.0	Featured

Disable
File sharing	1.19.0	Featured

Disable
Forms	3.4.2	Featured

Disable
Gestion	2.4.1	

Disable
Group folders	15.3.1	Featured

Disable
Impersonate	1.14.0	Featured

Disable
Log Reader	2.12.0	Featured

Disable
Mail	3.5.0	Featured

Disable
Maps	1.2.0	Featured

Disable
Mind Map	0.0.30	

Disable
Money	0.23.1	

Disable
Nextcloud All-in-One	0.4.0	

Disable
Nextcloud announcements	1.16.0	Featured

Disable
Notifications	2.15.0	Featured

Disable
Notifications for calendar event updates	2.3.0	

Disable
ONLYOFFICE	8.2.4	Featured

Disable
Password policy	1.17.0	Featured

Disable
PDF viewer	2.8.0	Featured

Disable
Polls	5.4.2	

Disable
Quota warning	1.18.0	

Disable
Registration	2.2.0	

Disable
Share by mail	1.17.0	Featured

Disable
Support	1.10.0	Featured

Disable
Suspicious Login	5.0.0	Featured

Disable
Talk	17.1.3	Featured

Disable
Tasks	0.15.0	Featured

Disable
Terms of service	2.3.1	

Disable
Text	3.8.0	Featured

Disable
Time Tracker	0.0.80	

Disable
TimeManager	0.3.10	

Disable
Unrounded Corners	1.1.2	

Disable
User status	1.7.0	Featured

Disable
Versions	1.20.0	Featured

Disable
Welcome	1.0.10	

Disable
YouTube integration	0.1.5	

Disable
Zipper	1.4.0	

Disable
```

**Comment by tacruc** [comment] 2023-12-12 20:09
If you get a black screen I would check the operating system and graphic card drivers.  Additionally the hardware. 
If it turns out that the screen is not black, screenshots and the browser console log would be helpful.

**Comment by punkyard** [comment] 2023-12-12 20:51
<img width="1412" alt="Capture d’écran 2023-12-12 à 21 49 40" src="https://github.com/nextcloud/maps/assets/59349105/a796c437-831b-4d15-a85e-6574980e1334">

**Comment by tacruc** [comment] 2023-12-12 22:18
Probably a duplicate of #1157

**Closed by tacruc** 2023-12-12 22:18 UTC
Labels: bug, 0. Needs triage

**Comment by punkyard** [comment] 2024-02-02 23:01
hi
thanks for the tip @tacruc 

but is it a duplicate? 
because I still get the exact same error right after install v1.2.0
on AiO 7.11.2
NC 27.1.5

```
Impossible de charger les contacts:
<div id="nojavascript">
<div>
Cette application requiert JavaScript pour fonctionner correctement. Veuillez <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">activer JavaScript</a> et recharger la page. </div>
</div>

Erreur interne du serveur
Le serveur est incapable d'exécuter votre requête.
Si cela se reproduit, veuillez envoyer les détails techniques ci-dessous à l'administrateur du serveur.
Le fichier journal du serveur peut fournir plus de renseignements.

Renseignements techniques
ID de la demande : 6BVXbLw883YhozVzQtXG
```

I got this log right after the install

`[index] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255) at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/src/Connection.php line 1814
    Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter->convert(["Doctrine\\DBAL ... "], ["Doctrine\\DBAL\\Query"])
 1. /var/www/html/3rdparty/doctrine/dbal/src/Connection.php line 1749
    Doctrine\DBAL\Connection->handleDriverException(["Doctrine\\DBAL ... "], ["Doctrine\\DBAL\\Query"])
 2. /var/www/html/3rdparty/doctrine/dbal/src/Connection.php line 1163
    Doctrine\DBAL\Connection->convertExceptionDuringQuery(["Doctrine\\DBAL ... "], "INSERT INTO \"o ... )", [";;CEM* (Collec ... "], [2,2,2,2,2,"And  ... "])
 3. /var/www/html/lib/private/DB/Connection.php line 295
    Doctrine\DBAL\Connection->executeStatement("INSERT INTO \"o ... )", [";;CEM* (Collec ... "], [2,2,2,2,2,"And  ... "])
 4. /var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 354
    OC\DB\Connection->executeStatement("INSERT INTO \"o ... )", ["3acbd425-5ae3- ... "], [2,2,2,2,2,"And  ... "])
 5. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/html/custom_apps/maps/lib/Service/AddressService.php line 298
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/html/custom_apps/maps/lib/Service/AddressService.php line 115
    OCA\Maps\Service\AddressService->scheduleForLookup(";;CEM* (Collect ... e", "a9304e5a-37b6-4 ... f")
 8. /var/www/html/custom_apps/maps/lib/Service/AddressService.php line 63
    OCA\Maps\Service\AddressService->lookupAddress(";;CEM* (Collect ... e", "a9304e5a-37b6-4 ... f")
 9. /var/www/html/custom_apps/maps/lib/Controller/ContactsController.php line 213
    OCA\Maps\Service\AddressService->addressToGeo(";;CEM* (Collect ... e", "a9304e5a-37b6-4 ... f")
10. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Maps\Controller\ContactsController->getContacts(null)
11. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Maps\\Con ... "], "getContacts")
12. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Maps\\Con ... "], "getContacts")
13. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OCA\\Maps\\Cont ... r", "getContacts", ["OC\\AppFramewo ... "], ["maps.contacts.getContacts"])
14. /var/www/html/lib/base.php line 1068
    OC\Route\Router->match("/apps/maps/contacts")
15. /var/www/html/index.php line 38
    OC::handleRequest()

Caused by:

Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255) at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php line 103
    Doctrine\DBAL\Driver\PDO\Exception::new(["PDOException", ... ]])
 1. /var/www/html/3rdparty/doctrine/dbal/src/Connection.php line 1153
    Doctrine\DBAL\Driver\PDO\Statement->execute()
 2. /var/www/html/lib/private/DB/Connection.php line 295
    Doctrine\DBAL\Connection->executeStatement("INSERT INTO \"o ... )", [";;CEM* (Collec ... "], [2,2,2,2,2,"And  ... "])
 3. /var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 354
    OC\DB\Connection->executeStatement("INSERT INTO \"o ... )", ["3acbd425-5ae3- ... "], [2,2,2,2,2,"And  ... "])
 4. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 5. /var/www/html/custom_apps/maps/lib/Service/AddressService.php line 298
    OC\DB\QueryBuilder\QueryBuilder->execute()
 6. /var/www/html/custom_apps/maps/lib/Service/AddressService.php line 115
    OCA\Maps\Service\AddressService->scheduleForLookup(";;CEM* (Collect ... e", "a9304e5a-37b6-4 ... f")
 7. /var/www/html/custom_apps/maps/lib/Service/AddressService.php line 63
    OCA\Maps\Service\AddressService->lookupAddress(";;CEM* (Collect ... e", "a9304e5a-37b6-4 ... f")
 8. /var/www/html/custom_apps/maps/lib/Controller/ContactsController.php line 213
    OCA\Maps\Service\AddressService->addressToGeo(";;CEM* (Collect ... e", "a9304e5a-37b6-4 ... f")
 9. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Maps\Controller\ContactsController->getContacts(null)
10. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Maps\\Con ... "], "getContacts")
11. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Maps\\Con ... "], "getContacts")
12. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OCA\\Maps\\Cont ... r", "getContacts", ["OC\\AppFramewo ... "], ["maps.contacts.getContacts"])
13. /var/www/html/lib/base.php line 1068
    OC\Route\Router->match("/apps/maps/contacts")
14. /var/www/html/index.php line 38
    OC::handleRequest()

Caused by:

PDOException: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255) at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php line 101
    PDOStatement->execute(null)
 1. /var/www/html/3rdparty/doctrine/dbal/src/Connection.php line 1153
    Doctrine\DBAL\Driver\PDO\Statement->execute()
 2. /var/www/html/lib/private/DB/Connection.php line 295
    Doctrine\DBAL\Connection->executeStatement("INSERT INTO \"o ... )", [";;CEM* (Collec ... "], [2,2,2,2,2,"And  ... "])
 3. /var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 354
    OC\DB\Connection->executeStatement("INSERT INTO \"o ... )", ["3acbd425-5ae3- ... "], [2,2,2,2,2,"And  ... "])
 4. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 5. /var/www/html/custom_apps/maps/lib/Service/AddressService.php line 298
    OC\DB\QueryBuilder\QueryBuilder->execute()
 6. /var/www/html/custom_apps/maps/lib/Service/AddressService.php line 115
    OCA\Maps\Service\AddressService->scheduleForLookup(";;CEM* (Collect ... e", "a9304e5a-37b6-4 ... f")
 7. /var/www/html/custom_apps/maps/lib/Service/AddressService.php line 63
    OCA\Maps\Service\AddressService->lookupAddress(";;CEM* (Collect ... e", "a9304e5a-37b6-4 ... f")
 8. /var/www/html/custom_apps/maps/lib/Controller/ContactsController.php line 213
    OCA\Maps\Service\AddressService->addressToGeo(";;CEM* (Collect ... e", "a9304e5a-37b6-4 ... f")
 9. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Maps\Controller\ContactsController->getContacts(null)
10. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Maps\\Con ... "], "getContacts")
11. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Maps\\Con ... "], "getContacts")
12. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OCA\\Maps\\Cont ... r", "getContacts", ["OC\\AppFramewo ... "], ["maps.contacts.getContacts"])
13. /var/www/html/lib/base.php line 1068
    OC\Route\Router->match("/apps/maps/contacts")
14. /var/www/html/index.php line 38
    OC::handleRequest()

GET /apps/maps/contacts
from 185.252.235.96 by neimen at 2024-02-02T22:54:46+00:00`

It would be really nice to be able to use this great tool!
