### ISSUE TITLE
Column name "oc_maps_address_geo"."object_uri" is NotNull, but has empty string or null as default.

### ISSUE THREAD

**Issue by vantino** [nextcloud/maps#502] opened 2020-11-21 16:39 UTC
INstallation issue, /w error msg

Column name "oc_maps_address_geo"."object_uri" is NotNull, but has empty string or null as default.

**Comment by michael-dev** [comment] 2020-11-22 17:16
+1

**Comment by michael-dev** [comment] 2020-11-22 17:30
Duplicate of #453

**Closed** 2020-11-22 17:33 UTC
