### ISSUE TITLE
The "unique" column option is not supported

### ISSUE THREAD

**Issue by J0WI** [nextcloud/maps#541] opened 2021-02-23 01:32 UTC
Error: Doctrine\DBAL\Schema\Exception\UnknownColumnOption: The "unique" column option is not supported.

<details><summary>details</summary>
```
 0. /var/www/html/3rdparty/doctrine/dbal/src/Schema/Column.php line 84
    Doctrine\DBAL\Schema\Exception\UnknownColumnOption::new("unique")
 1. /var/www/html/3rdparty/doctrine/dbal/src/Schema/Column.php line 68
    Doctrine\DBAL\Schema\Column->setOptions({notnull: true,length: 255,unique: true})
 2. /var/www/html/3rdparty/doctrine/dbal/src/Schema/Table.php line 355
    Doctrine\DBAL\Schema\Column->__construct("adr", Doctrine\DBAL\Types\StringType {}, {notnull: true,length: 255,unique: true})
 3. /var/www/html/custom_apps/maps/lib/Migration/Version000009Date20190625000800.php line 43
    Doctrine\DBAL\Schema\Table->addColumn("adr", "string", {notnull: true,length: 255,unique: true})
 4. /var/www/html/lib/private/DB/MigrationService.php line 455
    OCA\Maps\Migration\Version000009Date20190625000800->changeSchema(OC\Migration\SimpleOutput {}, Closure {}, {tablePrefix: "oc_"})
 5. /var/www/html/lib/private/DB/MigrationService.php line 418
    OC\DB\MigrationService->migrateSchemaOnly("latest")
 6. /var/www/html/lib/private/Installer.php line 163
    OC\DB\MigrationService->migrate("latest", true)
 7. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 448
    OC\Installer->installApp("maps")
 8. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 218
    OCA\Settings\Controller\AppSettingsController->enableApps(["maps"], [])
 9. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 127
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
10. /var/www/html/lib/private/AppFramework/App.php line 157
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
11. /var/www/html/lib/private/Route/Router.php line 302
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
12. /var/www/html/lib/base.php line 993
    OC\Route\Router->match("/settings/apps/enable")
13. /var/www/html/index.php line 37
    OC::handleRequest()
```
</details>

**Comment by gwenhael-le-moine** [comment] 2021-02-23 14:15
I get the same error with MariaDB 10.5.9 with a fresh install. When trying to enable Maps it fails with this error message.

**Comment by arnakazim** [comment] 2021-02-23 20:51
Just installed the latest version of Nextcloud (21.0.0) using SQLite and I get the same error when I try to enable the app.

**Comment by barti04** [comment] 2021-02-24 07:46
Same. Nextcloud 21 and MariaDB.

**Comment by pxlkng-dev** [comment] 2021-02-24 18:37
Same with Nextcloud 21.0.0.18 and MySQL 8

**Comment by bertieuk** [comment] 2021-02-24 19:04
Just got this, editted /var/www/nextcloud/apps/maps/lib/Migration/Version000009Date20190625000800.php and removed the two lines (45 & 50) containing 'unique' => true,

Now works, gave an sql error when first enabled but seems to be working now it's analysing photos.

**Comment by pxlkng-dev** [comment] 2021-02-24 23:49
> 
> 
> Just got this, editted /var/www/nextcloud/apps/maps/lib/Migration/Version000009Date20190625000800.php and removed the two lines (45 & 50) containing 'unique' => true,
> 
> Now works, gave an sql error when first enabled but seems to be working now it's analysing photos.

Yeah this may be a hotfix but no long-term solution, I dont want to have to temper with the files. That should be getting fixed by nextcloud/contributors for this app.

**Comment by snevas** [comment] 2021-03-10 10:48
Here is the nextcloud server issue:
https://github.com/nextcloud/server/issues/25607

It's broken for more apps.
I'm using docker fpm alpine image + sqlite db

**Comment by mchugh19** [comment] 2021-03-11 07:17
On a pretty new install of nextcloud 21, I was able to edit the migration script as suggested to remove the unique elements. This allowed me to install maps. However, while I can now browse to the maps app, nothing loads, and the logs show:
```
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_maps_tracks' doesn't exist
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_maps_favorite_shares' doesn't exist
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_maps_favorites' doesn't exist
```

Is there a way to re-run the table creation scripts?

**Comment by Tyil** [comment] 2021-03-11 13:22
On Wed, Mar 10, 2021 at 11:17:29PM -0800, Christian McHugh wrote:
> On a pretty new install of nextcloud 21, I was able to edit the migration script as suggested to remove the unique elements. This allowed me to install maps. However, while I can now browse to the maps app, nothing loads, and the logs show:
> ```
> Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_maps_tracks' doesn't exist
> Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_maps_favorite_shares' doesn't exist
> Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_maps_favorites' doesn't exist
> ```
> 
> Is there a way to re-run the table creation scripts?

Yes, using the occ utility in your Nextcloud directory.

occ migrations:execute maps <name>

The names of the migrations can be found in any app's lib/Migration directory,
but leave out the leading Version, and ending .php parts.

If Nextcloud complains they already ran, you can find the migration history in
the oc_migrations table in your database. Keep in mind that manually altering
records in this table might have unintended consequences. Ensure you have a
suitable backup before hacking around.

-- 
With kind regards,

Patrick Spek


www:  https://www.tyil.nl/
mail: ***@***.***
pgp:  1660 F6A2 DFA7 5347 322A  4DC0 7A6A C285 E2D9 8827

git:    https://git.tyil.nl/

**Comment by hakunamatata97k** [comment] 2021-03-15 17:56
nextcloud 21 with mariadb fresh install same error here!.

**Comment by localjo** [comment] 2021-03-15 21:28
I tried removing the `unique` lines, and now I'm getting another error:
```
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'contact_uid' doesn't exist in table
```

**Comment by localjo** [comment] 2021-03-15 21:57
@Tyil I apologize if this is an obvious question, but I'm new to NextCloud and I don't have any context. Does this occ utility need to be run in a terminal via ssh? I'm not sure if my provider gives me ssh access.

**Comment by oucil** [comment] 2021-03-16 21:12
Nextcloud 21 with MySQL8, same problem.

**Comment by Linux4win** [comment] 2021-03-17 10:19
The same issue arises with Postgres on Nextcloud 21.

**Comment by tacruc** [comment] 2021-03-19 17:13
Test of #568 are welcome.

**Comment by VoOoUoOoV** [comment] 2021-03-20 22:36
> 
> 
> Just got this, editted /var/www/nextcloud/apps/maps/lib/Migration/Version000009Date20190625000800.php and removed the two lines (45 & 50) containing 'unique' => true,
> 
> Now works, gave an sql error when first enabled but seems to be working now it's analysing photos.

After del this line 45&50, i got another error. 
Therefore i **rewrote " 'unique' => true  " back** to the lines 45 & 50. Then no errors occours. Dont know why it works, but it does..

**Comment by VoOoUoOoV** [comment] 2021-03-21 00:21
> 
> 
> Test of #568 are welcome.

Just testet it. Still not working.

**Comment by localjo** [comment] 2021-03-21 19:55
It looks like #568 fixes the problem. To get it to work, you need to disable the maps app, reset maps related database values, check out the fix branch, and then re-enable the maps app. Database commands are in #568 comments thread.

**Comment by VoOoUoOoV** [comment] 2021-03-22 14:58
Very Nice! `oc_maps_*` was missing in `oc_migrations`
This is how it works @ my NC-DB

1. Edit like described in #541
2. Deactivate maps app in Nextcloud
3. delete/drop @ DataBase: `app=maps` 
![grafik](https://user-images.githubusercontent.com/81052421/112009917-1e1af280-8b27-11eb-8998-19051bfa99e3.png)
4. Enable maps app in Nextcloud

`oc_maps_*` should be available and maps app works after a few minutes _(after auto scan via nextcloud)_

**Comment by tacruc** [comment] 2021-03-22 21:24
> Another Bug?
> After the contacts and pictures are shown in the maps, it is not possible to enlarge the pictures when choosing any.. Just seeing only the loading screen.

Probably you mean #543, or something else?

**Comment by VoOoUoOoV** [comment] 2021-03-22 21:32
> 
> 
> > Another Bug?
> > After the contacts and pictures are shown in the maps, it is not possible to enlarge the pictures when choosing any.. Just seeing only the loading screen.
> 
> Probably you mean #543, or something else?

Yes, Thank you very Much! Now it works :)

**Comment by Joshua2504** [comment] 2021-03-27 16:28
Same issue, latest nextcloud with mariadb.

**Comment by yuriry** [comment] 2021-03-27 23:41
The same issue

Nextcloud 21.0.0
PostgreSQL 12

![image](https://user-images.githubusercontent.com/16765548/112737874-1c806e80-8f1b-11eb-808d-bfc3792019e5.png)

**Comment by VoOoUoOoV** [comment] 2021-03-30 22:05
you can test [the nightly](https://github.com/nextcloud/maps/releases/tag/v0.1.9-8-nightly) or try [this](https://github.com/nextcloud/maps/issues/541#issuecomment-804129235) to fix it shortly. I used [webmin](https://webmin.com/) to edit the DB

**Comment by ThatCoffeeGuy** [comment] 2021-04-04 19:45
Same issue. Nextcloud 21.0.0 and Mysql 8

It might worth considering removing **a completely broken app** from **featured**.

Fortunately this worked:


1.) https://github.com/nextcloud/maps/issues/541#issuecomment-785304380
2.) disable maps
3.) mysql> DELETE FROM `oc_migrations` WHERE `app` LIKE "maps" ;
Query OK, 9 rows affected (0.01 sec)
4.) enable maps (ignore random syntax error..)
5.) $ sudo -u www-data php7.4 /var/www/nextcloud/occ maps:scan-photos

**Comment by gardinenstange** [comment] 2021-04-18 18:31
> Same issue. Nextcloud 21.0.0 and Mysql 8
> 
> It might worth considering removing **a completely broken app** from **featured**.
> 
> Fortunately this worked:
> 
> 1.) [#541 (comment)](https://github.com/nextcloud/maps/issues/541#issuecomment-785304380)
> 2.) disable maps
> 3.) mysql> DELETE FROM `oc_migrations` WHERE `app` LIKE "maps" ;
> Query OK, 9 rows affected (0.01 sec)
> 4.) enable maps (ignore random syntax error..)
> 5.) $ sudo -u www-data php7.4 /var/www/nextcloud/occ maps:scan-photos

didnt work :
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'contact_uid' doesn't exist in table

**Comment by lupinehorror** [comment] 2021-04-18 18:32
same error here with 21.0.1 on apache2 with mariadb v10.5.9 and php7.4

**Comment by Akruidenberg** [comment] 2021-04-25 10:36
same here. Using 21.0.0.1 with mariadb 10.3

**Comment by snevas** [comment] 2021-04-26 08:48
As stated [here](https://github.com/nextcloud/server/issues/25607), the nextcloud server will not support unique in the same way anymore. So the only hope is someone fixing it in the maps-app.

**Comment by deputyd0ng** [comment] 2021-04-29 21:47
Same issue, fresh nextcloud and mariadb install running in docker/unraid

**Comment by solmarcus** [comment] 2021-05-01 02:30
Same issue. This app is one of the main reasons I use NC, but I can't install it. 😭

**Comment by Redsandro** [comment] 2021-05-04 02:16
Same issue, using PostgreSQL 12.2.

**Comment by debdolph** [comment] 2021-05-04 20:11
Same issue on PostgreSQL 13…

**Comment by Redsandro** [comment] 2021-05-04 22:14
I manually installed the `0.1.9 nightly` and it works now. :+1: 

Manually installing apps is not ideal. We have the option to choose Nextcloud channels (stable, daily beta, production); we should similarly have the option to allow installing nighty (beta) app versions. 

Please thumbs up the relevant issue: https://github.com/nextcloud/server/issues/10487

**Comment by hobbsecky** [comment] 2021-05-09 04:46
> 
> 
> you can test [the nightly](https://github.com/nextcloud/maps/releases/tag/v0.1.9-8-nightly) or try [this](https://github.com/nextcloud/maps/issues/541#issuecomment-804129235) to fix it shortly. I used [webmin](https://webmin.com/) to edit the DB

Worked for me too on a clean NextcloudVM running NC 21.0.1. Thanks!

**Comment by saschamander** [comment] 2021-05-22 22:31
Just installed the [nightly build](https://apps.nextcloud.com/apps/maps/releases?platform=21#21) of Nextcloud/Maps manually and it worked like a charm.
I used docker and tested it with a fresh installation of version 21.0.1 and 21.0.2(current latest). Both work with the nightly build.

My steps where
1. Download nightly build of Nextcloud/Maps(link above)
2. Extract nightly build archive
3. Upload extracted maps-Folder to server into nextcloud/apps-Folder
4. Activate Maps via NC-WebInterface

**Comment by gianlucagiacometti** [comment] 2021-05-23 07:04
Confirmed, thanks

**Comment by ma-gh** [comment] 2021-05-24 19:01
> Very Nice! `oc_maps_*` was missing like in #566
> This is how it works @ my NC-DB
> similar to #568
> 
> 1. Edit like described [here](https://github.com/nextcloud/maps/commit/b7875f063bf86bb3385f6227bdaaeeebb59413fe)
> 2. Deactivate maps app in Nextcloud
> 3. In DataBase goto `oc_migrations` delete/drop: `app=maps`
>    ![grafik](https://user-images.githubusercontent.com/81052421/112009917-1e1af280-8b27-11eb-8998-19051bfa99e3.png)
> 4. Enable maps app in Nextcloud
> 
> `oc_maps_*` should be available and maps app works after a few minutes _(after auto scan via nextcloud)_
> 
> Another Bug?
> When you get the problem like loading screen for pictures ( #543 ), then you can fix it with edit [this](https://github.com/nextcloud/maps/commit/2bd43bc28dacd798c48fd90fcac9575d22989f5e)

I did not have to drop anything from the Database, enabled via occ after editing files.
Thank you!

**Comment by rugk** [comment] 2021-05-30 16:16
With Nextcloud 21.0.2.1 and a fresh installation of Maps  0.1.8 (never installed/enabled before) this error also happens at installation time.
So I cannot "disable and re-enable it", as I cannot install it in the first place (via the web interface, at least).

Given that a fix has been integrated already if I read this issue correctly, what is stopping you from releasing the new version now?

**Comment by joshdmwood** [comment] 2021-06-02 02:35
> Just installed the [nightly build](https://apps.nextcloud.com/apps/maps/releases?platform=21#21) of Nextcloud/Maps manually and it worked like a charm.
> I used docker and tested it with a fresh installation of version 21.0.1 and 21.0.2(current latest). Both work with the nightly build.
> 
> My steps where
> 
>     1. Download nightly build of Nextcloud/Maps(link above)
> 
>     2. Extract nightly build archive
> 
>     3. Upload extracted maps-Folder to server into nextcloud/apps-Folder
> 
>     4. Update Owner/Group (with chown)
> 
>     5. Activate Maps via NC-WebInterface
> 
> 
> EDIT:
> If you want to have the stable version, you can disable and remove Maps again via the NC-WebInterface.
> Also you will have to delete the maps folder from the nextcloud/apps-Folder.
> After that you should be able to download and activate Maps in the current stable version.
> (Though it seems I can't load my GPX-Tracks, but that is another issue)

Confirmed as well, running NextCloud 21.0.2 with MariaDB 10.3.28 on CentOS 8 with php74-fpm
download, extract in apps folder (replacing existing maps folder) and enable in your applications in nextcloud

**Comment by snowphone** [comment] 2021-06-05 15:21
I just started NextCloud a week ago, and found this issue recently.

Thus, do you guys know how long it takes to be stabilized? I'm planning to download 0.1.9 when it becomes stable, but I'm not sure how long should I wait for.

**Comment by alehaa** [comment] 2021-06-06 17:20
I can confirm 0.1.9 works quite well, at least for those never have used it before. Just downloaded and copied it into the `/apps` subdirectory and works like a charm.

**Comment by AgentCasey** [comment] 2021-06-23 20:47
I think that I may have a solution to this issue; cd to /var/www/nextcloud/apps/maps/lib/Migration and move all *.php files to somewhere for safekeeping. The directory should now be empty, then install the app again. It should install and act properly now. Thanks.

**Comment by tacruc** [comment] 2022-04-14 10:35
I would summarize that #568 fixes this issue.
There might be a still be a problem with old tables,  therefore I would like to point to https://github.com/nextcloud/maps/pull/568#issuecomment-803649323.

**Closed by tacruc** 2022-04-14 10:35 UTC
Labels: bug
