### ISSUE TITLE
Error installing Maps

### ISSUE THREAD

**Issue by p6002** [nextcloud/maps#500] opened 2020-11-18 17:12 UTC
I am trying to install the maps 0.1.6 application from the store and I have an error:

"Column name "oc_maps_address_geo"."object_uri" is NotNull, but has empty string or null as default. "

My setup:
NextCloudPi version | v1.31.0
-- | --
NextCloudPi image | NextCloudPi_09-05-20

**Comment by qnarkill** [comment] 2020-11-21 12:47
[settings] Error: InvalidArgumentException: Column name "oc_maps_address_geo"."object_uri" is NotNull, but has empty string or null as default. at <<closure>>

 0. /var/www/nextcloud/lib/private/DB/MigrationService.php line 484
    OC\DB\MigrationService->ensureOracleIdentifierLengthLimit(Doctrine\DBAL\Schema\Schema {}, Doctrine\DBAL\Schema\Schema {}, 3)
 1. /var/www/nextcloud/lib/private/DB/MigrationService.php line 414
    OC\DB\MigrationService->executeStep("000013Date20190723185417", false)
 2. /var/www/nextcloud/lib/private/Installer.php line 157
    OC\DB\MigrationService->migrate()
 3. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 447
    OC\Installer->installApp("maps")
 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Settings\Controller\AppSettingsController->enableApps(["maps"], [])
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
 6. /var/www/nextcloud/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
 7. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
 9. /var/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
10. /var/www/nextcloud/lib/base.php line 1011
    OC\Route\Router->match("/settings/apps/enable")
11. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

POST /settings/apps/enable
by ncp at 2020-11-21T12:36:57+00:00

same here  Maps 0.1.6, NextCloudPi 19.0.4

**Comment by michael-dev** [comment] 2020-11-22 17:30
Duplicate of #453

**Closed** 2020-11-23 13:28 UTC
