### ISSUE TITLE
Build v0.1.5 fails npm ERR! 429 Too Many Requests

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#300] opened 2020-02-17 11:49 UTC
@gary-kim @paulschwoerer @eneiluj @jancborchardt 
I'm not able to build the new relase. 

make fails with:
```
make composer
make[1]: Verzeichnis „/srv/www/htdocs/server/apps/maps“ wird betreten
composer install --prefer-dist
PHP Warning:  PHP Startup: gnupg: Unable to initialize module
Module compiled with module API=20180731
PHP    compiled with module API=20190902
These options need to match
 in Unknown on line 0
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
composer update --prefer-dist
PHP Warning:  PHP Startup: gnupg: Unable to initialize module
Module compiled with module API=20180731
PHP    compiled with module API=20190902
These options need to match
 in Unknown on line 0
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
make[1]: Verzeichnis „/srv/www/htdocs/server/apps/maps“ wird verlassen
make npm
make[1]: Verzeichnis „/srv/www/htdocs/server/apps/maps“ wird betreten
/usr/bin/npm install
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/optimize/FlagIncludedChunksPlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/getFunctionExpression.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/buildin/global.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/buildin/harmony-module.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyAcceptDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyAcceptImportDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyCompatibilityDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyDetectionParserPlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyExportDependencyParserPlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyExportExpressionDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyExportHeaderDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyExportImportedSpecifierDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyExportSpecifierDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyImportDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyImportDependencyParserPlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyImportSideEffectDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyImportSpecifierDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyInitDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyModulesPlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/HarmonyTopLevelThisParserPlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/util/identifier.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/ImportContextDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/ImportDependenciesBlock.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/ImportDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/ImportEagerDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/ImportParserPlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/ImportPlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/ImportWeakDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/dependencies/JsonExportsDependency.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/web/JsonpChunkTemplatePlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/web/JsonpExportMainTemplatePlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/web/JsonpHotUpdateChunkTemplatePlugin.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/web/JsonpMainTemplate.runtime.js'
npm WARN tar ENOENT: no such file or directory, open '/srv/www/htdocs/server/apps/maps/node_modules/.staging/webpack-bcde39bb/lib/web/JsonpMainTemplatePlugin.js'
npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/install/-/install-0.13.0.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arne/.npm/_logs/2020-02-17T11_45_14_006Z-debug.log
make[1]: *** [Makefile:89: npm] Fehler 1
make[1]: Verzeichnis „/srv/www/htdocs/server/apps/maps“ wird verlassen
make: *** [Makefile:65: build] Fehler 2
```

Does anyone has an idea how to solve

```
npm ERR! code E429
npm ERR! 429 Too Many Requests
```
?

**Comment by JerryWang20** [comment] 2020-02-17 12:06
i meet the same issue, is it caused by NPM official site?

**Comment by Niekes** [comment] 2020-02-17 12:06
We have the same issue! 

`429 Too Many Requests - GET https://registry.npmjs.org/register-service-worker`

It looks more like a NPM issue.

**Comment by ToonvanStrijp** [comment] 2020-02-17 12:06
@Niekes same issue here :(

**Comment by alesten** [comment] 2020-02-17 12:07
We are having same issue as well

**Comment by wiseelf** [comment] 2020-02-17 12:07
`17-Feb-2020 11:47:48	npm ERR! code E429`
`17-Feb-2020 11:47:48	npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/@babel/plugin-transform-block-scoping/-/plugin-transform-block-scoping-7.8.3.tgz`

Same issue here.

**Comment by nazeefahmadmeer** [comment] 2020-02-17 12:08
If you are using Circle CI? Then it is having an issue with npm atm: https://status.circleci.com

**Comment by chriscummings100** [comment] 2020-02-17 12:12
Not using nextcloud, but I'm suddenly experiencing the same errors just attempting to do a google cloud build (which does an npm install). Guessing this is an npm issue.

**Comment by jannikbuschke** [comment] 2020-02-17 12:12
I am seeing errors like
```
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/is-plain-object/-/is-plain-object-
```
and
```
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/@lerna/cli/-/cli-3.13.0.tgz
```
On a different project with AzureDevops CI. I assume its something with npm.

**Comment by haytham-salhi** [comment] 2020-02-17 12:12
We have same issue here!

**Comment by MajcenT** [comment] 2020-02-17 12:13
I have the same issue

**Comment by astrovpls** [comment] 2020-02-17 12:13
Same

**Comment by LeeJCherry** [comment] 2020-02-17 12:14
Same issue here within the last 1 hour.  Pipelines been fine all morning, no changes, now getting this

npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/infer-owner

**Comment by ksemtinimahmoud** [comment] 2020-02-17 12:15
same issue here

**Comment by Velfix** [comment] 2020-02-17 12:15
Same, it´s down:

https://bitbucket.status.atlassian.com/

**Comment by ZLTM** [comment] 2020-02-17 12:18
Same problem while doing npm install, not even related to maps, this looks like an npm issue

**Comment by lipikadugar** [comment] 2020-02-17 12:20
Facing the same issue while doing `npm install`

**Comment by darwin-gautalius** [comment] 2020-02-17 12:21
facing the same issue

**Comment by fsebbane** [comment] 2020-02-17 12:22
Same issue

**Comment by shubhamholkar007** [comment] 2020-02-17 12:27
Same Here while creating react app

**Comment by ZLTM** [comment] 2020-02-17 12:28
Tried `npm install` on a different machine and everything is normal, the previous machine is still failing with E429

**Comment by RomaMelnyk** [comment] 2020-02-17 12:32
Where the button "same"?

**Comment by sbishakafenix** [comment] 2020-02-17 12:32
Facing the issue, CI builds failing with e429 for about 3 hours now

**Comment by juroMin** [comment] 2020-02-17 12:36
facing the same issue

**Comment by BashisthaSudeep** [comment] 2020-02-17 12:36
Same issue here
`npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/postcss-merge-longhand/-/postcss-merge-longhand-4.0.11.tgz`

**Comment by MuriloEduardo** [comment] 2020-02-17 12:37
Same issue here

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: is-number@4.0.0 (node_modules/randomatic/node_modules/is-number):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 429 Too Many Requests - GET https://registry.npmjs.org/is-number/-/is-number-4.0.0.tgz
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: randomatic@3.1.1 (node_modules/randomatic):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 429 Too Many Requests - GET https://registry.npmjs.org/randomatic/-/randomatic-3.1.1.tgz
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: preserve@0.2.0 (node_modules/preserve):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 429 Too Many Requests - GET https://registry.npmjs.org/preserve/-/preserve-0.2.0.tgz
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: parse-glob@3.0.4 (node_modules/parse-glob):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 429 Too Many Requests - GET https://registry.npmjs.org/parse-glob/-/parse-glob-3.0.4.tgz

npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/babel-plugin-transform-es2015-computed-properties/-/babel-plugin-transform-es2015-computed-properties-6.24.1.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/murilo/.npm/_logs/2020-02-17T12_32_50_795Z-debug.log
```

**Comment by JaGu25** [comment] 2020-02-17 12:38
Same issue here :/

**Comment by dieffrei** [comment] 2020-02-17 12:38
Same here

**Comment by brandaoplaster** [comment] 2020-02-17 12:38
Same issue here :(
npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/cryptiles

**Comment by ArzelaAscoIi** [comment] 2020-02-17 12:38
same 
```
npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-1.1.3.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-17T12_36_38_124Z-debug.log
```

**Comment by veslav3** [comment] 2020-02-17 12:39
I see a lot of recent postings, but I have the same issue with another project, so it's not related to nextcloud probably.

**Comment by DaveWoody** [comment] 2020-02-17 12:39
Found this via Google. Same issue with a docker installation. Thought i would go insane.

**Comment by Linkels** [comment] 2020-02-17 12:40
Since one hours, impossible to install :/

npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/make-fetch-happen

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Linkels\AppData\Roaming\npm-cache\_logs\2020-02-17T12_34_46_787Z-debug.log

**Comment by glauber-sampaio** [comment] 2020-02-17 12:42
Same here 

`npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/@babel/plugin-transform-arrow-functions/-/plugin-transform-arrow-functions-7.8.3.tgz`

**Comment by Anthonipples** [comment] 2020-02-17 12:43
Same issue here on an Ionic npm install, NPM is limiting requests for some reason, you can watch the NPM output carfully and see that vaarious failures will happen after 4 retries

**Comment by vdanyliv** [comment] 2020-02-17 12:43
samw

**Comment by 0x-genesys** [comment] 2020-02-17 12:43
I am also getting :

```
npm ERR! code E429
npm ERR! 429 Too Many Requests
```


in us-east-1 was container , every time I try to build/ run "npm install"

**Comment by Obermair** [comment] 2020-02-17 12:44
same here 
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/@babel%2fplugin-transform-parameters

**Comment by hamzatekin** [comment] 2020-02-17 12:45
same here too!

`npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/d3-hierarchy/-/d3-hierarchy-1.1.5.tgz`

**Comment by mukarav** [comment] 2020-02-17 12:45
Same issue here. How to fix it.

**Comment by servernope** [comment] 2020-02-17 12:46
same...
npm ERR! code E429

**Comment by kornblum** [comment] 2020-02-17 12:46
https://github.com/npm/cli/issues/836

**Comment by ZLTM** [comment] 2020-02-17 12:47
same problem when trying to install browser-sync

**Comment by vladpazych** [comment] 2020-02-17 12:48
Use yarn for now. It works...

**Comment by Kais-ben-youssef** [comment] 2020-02-17 12:51
Same here. But no update of a problem yet on their [status page ](https://status.npmjs.org/). Weird !

**Comment by mukarav** [comment] 2020-02-17 12:51
How to avoid this issue ,can we use private registry. This could solve the problem.. what is permanent fix.

**Comment by MuriloEduardo** [comment] 2020-02-17 12:55
![Captura de Tela 2020-02-17 às 09 55 12](https://user-images.githubusercontent.com/13341227/74655749-a2a08200-516b-11ea-9bf1-542289835f64.png)

started to investigate

**Comment by dfloresdev** [comment] 2020-02-17 12:56
You can see the status of npm in the next link:
https://status.npmjs.org/

**Comment by KaraTee** [comment] 2020-02-17 12:58
Same error here
npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/rxjs/-/rxjs-6.5.4.tgz

**Comment by Anthonipples** [comment] 2020-02-17 12:59
https://status.npmjs.org/
 they have acknowledged it

**Comment by DEVESHKUMAR97** [comment] 2020-02-17 13:00
Its been fixed now!

**Comment by alisamina0** [comment] 2020-02-17 13:01
Yes it is fixed!!!

**Comment by MuriloEduardo** [comment] 2020-02-17 13:02
fixed up! let's work again

**Comment by Williamhssilva** [comment] 2020-02-17 13:02
-npm update

**Comment by acalbet** [comment] 2020-02-17 13:02
Yess!!

**Comment by ga0125** [comment] 2020-02-17 13:03
Guys, npm worked for me again.

**Comment by gokselb** [comment] 2020-02-17 13:07
Yesss! It has worked.

**Closed** 2020-02-17 13:10 UTC
Labels: bug
