### ISSUE TITLE
Integration with existing OSM-based voluntary mapping environments

### ISSUE THREAD

**Issue by almereyda** [nextcloud/maps#122] opened 2019-09-04 07:43 UTC
Where it is said that integration of Maps with Gnome Maps and alike can be expected, integration with further existing mapping environments may aid in anticipating ways of solving #12 #70.

Offline mapping environments like

* [Maps | F-Droid - Free and Open Source Android App Repository](https://f-droid.org/de/packages/com.github.axet.maps/)
* [OsmAnd~ | F-Droid - Free and Open Source Android App Repository](https://f-droid.org/de/packages/net.osmand.plus/)
* [PocketMaps | F-Droid - Free and Open Source Android App Repository](https://f-droid.org/de/packages/com.junjunguo.pocketmaps/)
* [MAPS.ME – Offline-Karten, Navigation, Reisefuhrer – Apps bei Google Play](https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro)
* [Mapy.cz - Cycling & Hiking offline maps – Apps bei Google Play](https://play.google.com/store/apps/details?id=cz.seznam.mapy)

may be a source of or possible partner to share offline map tiles and the curation of favourites with.

Personal and collaborative online mapping environments like

* [uMap – OpenStreetMap Wiki](https://wiki.openstreetmap.org/wiki/UMap)
* [Qwant Maps - Beta](https://www.qwant.com/maps/)
  * [qwantmaps/contributing.md at master · QwantResearch/qwantmaps](https://github.com/QwantResearch/qwantmaps/blob/master/contributing.md)

may additionally aid in republishing such custom maps and importing existing layers.

**Comment by tacruc** [comment] 2019-09-04 10:06
How are your ideas related to the Ideas in Issue #92?

**Comment by SomeStrangeName** [comment] 2019-09-15 12:41
For uMap an import works already, only issue: nextcloud/maps does not support all of the fields.
They are just shown as a not editable list of key-value pairs.

I hope nextcloud/maps could add some of the fields and maybe there could be an import filter sooner or later? Such a filter could ask for the "type" of GPX file and could than map specific fields (for example from uMap) to existing fields in nextcloud/maps.

Example fields that could be editable and mapped:

- Color for items
- maybe the icon (if it is unicode)
- probably an URL?

Here is an example URL:
https://umap.openstreetmap.fr/de/map/unbenannte-karte_364968#6/51.007/1.989
I just added one example poi randomly.
So would be easy to create test data for import tests.

A real sync could be more complex, maybe import/export would be a good first step?

**Comment by jancborchardt** [comment] 2019-09-17 10:47
Closing this as a duplicate of https://github.com/nextcloud/maps/issues/92, let’s continue there. :)

@SomeStrangeName could you open a new issue about this specific issue of the additional fields not being editable? :) We could indeed have an "Additional fields" functionality showing those. They would not be shown by default if not used, but still accessible.

**Closed by jancborchardt** 2019-09-17 10:47 UTC
Labels: duplicate, enhancement, feature: 🗺 map
