### ISSUE TITLE
Show Images from Groupfolders

### ISSUE THREAD

**Issue by ryeex-git** [nextcloud/maps#797] opened 2022-07-24 19:34 UTC
Is there a way to add Images from [Groupfolders](https://github.com/nextcloud/groupfolders) into the map? 
(Like the normal uploaded Images, which are not in the Groupfolders)

**Comment by aalcaine** [comment] 2022-08-12 07:48
It would be great to do it :(

**Comment by nstoeckigt** [comment] 2022-08-27 00:47
Duplicate of https://github.com/nextcloud/maps/issues/447

**Closed** 2022-08-27 07:54 UTC
