### ISSUE TITLE
Maps breaks execution of cron.php

### ISSUE THREAD

**Issue by DrRSatzteil** [nextcloud/maps#278] opened 2020-01-27 20:40 UTC
Hi,

I just realized that background jobs are no longer executed on my nextcloud instance. The logs show that this is due to a null pointer in a background job of the Maps app (see log)

`Error cron2020-01-27T21:25:02+0100
Error: Call to a member function getUserFolder() on null
/var/www/html/lib/public/BackgroundJob/Job.php - line 77:`

`OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run({ fileId: 47 ... "})`

`/var/www/html/lib/public/BackgroundJob/QueuedJob.php - line 46:`

`OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})`

`/var/www/html/cron.php - line 124:`

`OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})`

After disabling the Maps app, everything works fine again.

**Comment by DrRSatzteil** [comment] 2020-01-27 20:43
I'm using the latest Maps 0.1.4 release btw.

**Comment by tacruc** [comment] 2020-01-27 21:22
duplicate of #247.

**Closed by tacruc** 2020-01-27 21:22 UTC
