### ISSUE TITLE
Division by zero error when adding photos

### ISSUE THREAD

**Issue by sirjaymond** [nextcloud/maps#361] opened 2020-04-16 07:48 UTC
So I'm getting the below error under the following circumstances:
[PHP] Error: Division by zero at /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php#407

I have a bunch of photos uploaded to NextCloud. I then add them to the scan job with the following command:
docker exec --user www-data nextcloud php occ maps:scan-photos

The next time the cron job runs, I get the division by zero error, and none of the photos appear on the map.
The error is not happening for photos that I've recently uploaded through the Android app, and these seem to be added to the map just fine.
The photos giving the error were taken previously, and uploaded via the Linux desktop app.

Thanks

**Comment by tacruc** [comment] 2020-04-16 09:12
Fist of all you don't need to run maps:scan-photos, after you uploaded pictures. maps:scan-photos will triger a full rescan of all files. When a file is uploaded a scan of this file is automatically scheduled.

Related to #123.

Can you email me one sample picture, where the error occurs. Than I can see what's the exact problem. Otherwise I can just silence the error message by skipping the image.

**Comment by sirjaymond** [comment] 2020-04-16 10:45
Hi,

Thanks for your reply. I've done a bit more digging, and it looks like an issue with the GPS data on these photos... they seemed to be showing all 000's.  Funny thing is that the originals on my phone still had intact GPS data, so i'm not sure where the issue lies.



-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


16 Apr 2020, 19:12 by notifications@github.com:

**Comment by tacruc** [comment] 2020-04-17 14:03
I will close this issue as it seams to be a problem with the exif data.

**Closed by tacruc** 2020-04-17 14:03 UTC

**Comment by ggeorgg** [comment] 2020-04-27 18:42
I also found some lines in my log with this error:
Division by zero at /srv/www/nextcloud/apps/maps/vendor/lsolesen/pel/src/PelCanonMakerNotes.php#229
I guess it is also a problem that needs to be solved in the external library. Nevetheless, can we apply a catch for these lines as well? Where would I need to insert the logger line to get the path to these "broken" images? Is it the same as in the other issue?

**Comment by tacruc** [comment] 2020-04-28 07:02
Is the same as the other. The pel library is only used once to get exif data. And it is only a backup if the PHP internal function is not working for what ever reason.

**Comment by AykutCevik** [comment] 2020-06-11 09:08
@sirjaymond how did you upload the pictures so the originals had the GPS data but the uploaded ones not?

**Comment by TheBluestBird** [comment] 2021-03-21 15:37
> I will close this issue as it seams to be a problem with the exif data.
I'm so sorry, but the cron job just silently fails because of that, and this is okay for you? No need to check or try-catch, or whatever you have there in php? The leak is on the other side of the boat?
How do I run my cron jobs again? I have no clue which of gazillons of pictures my users uploaded have wrong exif, how do I even find it?

**Comment by tacruc** [comment] 2021-03-21 16:49
I'm totally fine by this. I'm programming this in my free time which works for my usecases and you can use for free.
My cronjob is starting ever 5 minutes. I don't care if it crashed some time.

You might try to fix the catch block in https://github.com/nextcloud/maps/blob/b2af5dd14a786501f0df451d0152a7179188b2c6/lib/Service/PhotofilesService.php#L385

It might help to replace PelException with Exception. I'm happy to review your PR.

> > I will close this issue as it seams to be a problem with the exif data.
> 
> I'm so sorry, but the cron job just silently fails because of that, and this is okay for you? No need to check or try-catch, or whatever you have there in php? The leak is on the other side of the boat?
> How do I run my cron jobs again? I have no clue which of gazillons of pictures my users uploaded have wrong exif, how do I even find it?

I'm totally fine by this. I'm programming this in my free time which works for my usecases and you can use for free.
My cronjob is starting ever 5 minutes. I don't care if it crashed some time.

You might try to fix the catch block in https://github.com/nextcloud/maps/blob/b2af5dd14a786501f0df451d0152a7179188b2c6/lib/Service/PhotofilesService.php#L385

It might help to replace PelException with Exception. I'm happy to review your PR.

**Comment by TheBluestBird** [comment] 2021-03-21 17:57
No, man, I'm sorry, I have a birthday today, and I have wasted it trying to figure out why my people don't see new files. Last place I thought it could be - is the maps app.
There you go, I have added some catches with new kind of exception appeared only in php8, that solved it for me and my cron is running now. If you care about other people cron jobs never been executed because of this silly poop - you should add it yourself 
https://www.php.net/manual/en/class.divisionbyzeroerror.php

**Comment by tacruc** [comment] 2021-03-21 18:12
I'm quite aware of the php docs. Thanks for posting it anyways, have fun on your birthday.

**Comment by mxm-tr** [comment] 2022-07-15 17:02
The issue is still occurring on Maps 0.1.10 in my Nextcloud 24.0.2 install , the line number is now different though

```
DivisionByZeroError: Division by zero in /var/www/html/apps/maps/lib/Service/PhotofilesService.php:413
Stack trace:
#0 /var/www/html/apps/maps/lib/Service/PhotofilesService.php(264): OCA\Maps\Service\PhotofilesService->getExif(Object(OC\Files\Node\File))
#1 /var/www/html/apps/maps/lib/BackgroundJob/AddPhotoJob.php(56): OCA\Maps\Service\PhotofilesService->addPhotoNow(Object(OC\Files\Node\File), 'mxmtr')
#2 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\Maps\BackgroundJob\AddPhotoJob->run(Array)
#3 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#4 /var/www/html/cron.php(151): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
```

The line is the following:
```
$gps[$key] = $temp[0] / $temp[1];
```

I manually patched it with the code from https://github.com/nextcloud/maps/pull/648 and the error is gone now, maybe this PR could be merged? Thanks!
