### ISSUE TITLE
Only own upload photos viewable :(

### ISSUE THREAD

**Issue by jojo-gfx** [nextcloud/maps#657] opened 2021-11-07 16:11 UTC
Hi,

was testing maps plugin and I find it sooooo good! 
But, at time it is relative useless and only the user itself can see his own photos on the map. So the usage options are nearly zero... only just for fun, wow, it works.

This is so because the maps-plugin is ignoring all colaborative functions oh Nextcloud and this is a bad thing.

Here a suggestion for "Give them a sense!" ... create one special named or tagged folder (e.g. map-media-folder) for every user. Only what is there (also in folders) is showing in the map. So if he like, he can put his media all there or also he can do an selection for map view.
In the map app itself it would be nice, there will shown all this folders of users who is sharing his "map-media-folder" with you as menu point for check in and out.

With this easy way it will be easier for the system find and create metadata because not all files on server are to crawl for it and also you can share your data with friends in this charming way. 
That would be sooo great!

The absolute top point feature would be to make a map with own photos accessible for creating a link for externals, but think that would be not so easy, especcially the logic behind. ;)

What do you think about this sharing possibilitys?
Greetings and thanks for this good work!

**Comment by shawnhaigh** [comment] 2021-11-28 08:41
+1 for this feature request! 

It would be great especially for hiking groups/clubs to share photos and tracks as well as for families. For example If I receive a shared folder from my partner containing tracks or photos maps should index and display these and provide a toggle in the left side bar like "Shared Photos"  or "Shared Tracks".

Non the less, I still enjoy this NextCloud App! Keep up the great work.

**Comment by jojo-gfx** [comment] 2021-11-28 09:21
Yes, to build up a hiking group server was my intension but on try I was more and more frustrated because nothing works with other users. At time the map is only just for fun and not productive usable.

**Comment by kovge** [comment] 2022-01-11 21:48
+1 for this feature reqest. Would be awesome to see all available (shared by others) photosbas well.

**Comment by wiktorsikora** [comment] 2022-03-20 09:30
Duplicate of https://github.com/nextcloud/maps/issues/447

**Closed** 2022-03-20 16:24 UTC
