### ISSUE TITLE
Error install app in Nextcloud 15.0.12

### ISSUE THREAD

**Issue by danyocean** [nextcloud/maps#175] opened 2019-10-01 10:05 UTC
I try to install you app in my Nextcloud, but i receive this error:

An exception occurred while executing 'CREATE TABLE oc_maps_address_geo (id BIGINT AUTO_INCREMENT NOT NULL, adr VARCHAR(255) NOT NULL, adr_norm VARCHAR(255) NOT NULL, lat DOUBLE PRECISION DEFAULT NULL, lng DOUBLE PRECISION DEFAULT NULL, looked_up TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_4C2424AB9CEC6B64C4BE9D6 (adr, adr_norm), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Can you help me please?

Regards

**Comment by tacruc** [comment] 2019-10-01 10:18
Duplicate of #109

**Closed by tacruc** 2019-10-01 10:18 UTC
