### ISSUE TITLE
.nomedia file not respected

### ISSUE THREAD

**Issue by dennorske** [nextcloud/maps#228] opened 2019-12-30 10:54 UTC
## Description
Android does have a feature where folders will not be scanned for media, as long as the root folder of the desired directory contains a .nomedia file. 
Same goes for the Gallery App on nextcloud, I can simply put a .nomedia file in my backup folder, and the gallery will respect that it shouldn't scan this folder and its subfolders.

## Suggestion
Add something like this for maps, when you scan media. It is currently indexing all my backup folders and this is not necessary. If it is already present, how do I go forward to block thiis?
I tried with .nomedia, however it scans the folders.

**Comment by jancborchardt** [comment] 2019-12-30 11:10
Yep, scanning should probably skip those folders. Has to be implemented, and any help is welcome. :) cc @nextcloud/maps

**Comment by dennorske** [comment] 2020-01-18 21:50
Related to #143

**Comment by jancborchardt** [comment] 2020-01-27 05:05
Thanks @dennorske – closing this as duplicate of https://github.com/nextcloud/maps/issues/143

**Closed by jancborchardt** 2020-01-27 05:05 UTC
Labels: enhancement, feature: :mountain_biking_woman:   tracks, feature: 🖼 photos
