### ISSUE TITLE
cron fails after occ maps:scan-photos

### ISSUE THREAD

**Issue by Emporea** [nextcloud/maps#656] opened 2021-11-04 16:31 UTC
NC: 22.2
docker-compose
Maps: latest

cron wont run anymore after a manual occ maps:scan-photos.

even removing maps / restarting the system wont help... I am stuck.

![image](https://user-images.githubusercontent.com/21969523/140379632-b42aefc0-6cd6-4644-890a-2598c5071c91.png)

Log shows this
```
[cron] Error: Unsupported operand types: int * string

at 2021-11-04T16:25:00+00:00
```
`{"reqId":"fkYarwElFKfKTrFxGxok","level":3,"time":"2021-11-04T16:25:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Unsupported operand types: int * string","userAgent":"--","version":"22.2.0.2","exception":{"Exception":"TypeError","Message":"Unsupported operand types: int * string","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php","line":368,"function":"loadSingleValue","class":"lsolesen\\pel\\PelIfd","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"},175,24,0]},{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php","line":350,"function":"load","class":"lsolesen\\pel\\PelIfd","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"},175]},{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelTiff.php","line":159,"function":"load","class":"lsolesen\\pel\\PelIfd","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"},10]},{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelExif.php","line":108,"function":"load","class":"lsolesen\\pel\\PelTiff","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"}]},{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php","line":216,"function":"load","class":"lsolesen\\pel\\PelExif","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"}]},{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php","line":126,"function":"load","class":"lsolesen\\pel\\PelJpeg","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"}]},{"file":"/var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php","line":442,"function":"__construct","class":"lsolesen\\pel\\PelJpeg","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"}]},{"file":"/var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php","line":384,"function":"getExifPelBackup","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"}]},{"file":"/var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php","line":264,"function":"getExif","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"}]},{"file":"/var/www/html/custom_apps/maps/lib/BackgroundJob/AddPhotoJob.php","line":56,"function":"addPhotoNow","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},"emporea"]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Maps\\BackgroundJob\\AddPhotoJob","type":"->","args":[{"photoId":43292,"userId":"emporea"}]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":47,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/html/cron.php","line":127,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php","Line":447,"CustomMessage":"--"},"id":"61840a661b38f"}`

**Comment by elearningdienst** [comment] 2021-11-18 10:34
Same here. I think this issue is related to https://github.com/nextcloud/maps/issues/652

**Comment by umgfoin** [comment] 2022-01-21 08:43
Duplicate of #640

**Closed** 2022-03-15 09:37 UTC
Labels: bug, duplicate
