### ISSUE TITLE
occ scan photos failed

### ISSUE THREAD

**Issue by azazjjyjjy** [nextcloud/maps#137] opened 2019-09-06 13:44 UTC
...
[40105] Photo "/files/Shared/Photos (2)/18-11-17 18-59-29 5775.jpg" added
[40106] Photo  "/files/Shared/Photos (2)/18-11-17 19-02-58 5776.jpg" added
mmap() failed: [12] Cannot allocate memory
Killed

I have increased the php memory from 512 to 2048M. What can I do then?
#126 #128

**Comment by tacruc** [comment] 2019-09-06 13:54
Well it seems to be a problem that there is not enough memory available on the server. But if you still have free ram or swap than maybe https://stackoverflow.com/questions/27634109/why-mmap-cannot-allocate-memory might help. Otherwise buy more Ram or wait until #126 is fixed.

**Comment by azazjjyjjy** [comment] 2019-09-06 13:58
> Well it seems to be a problem that there is not enough memory available on the server. But if you still have free ram or swap than maybe https://stackoverflow.com/questions/27634109/why-mmap-cannot-allocate-memory might help. Otherwise buy more Ram or wait until #126 is fixed.

My server has 8G memory so I think it's not physical memory limit, I will try the link you sent, thank you!
                 total           used        free      shared  buff/cache   available
Mem:           8265         281        7785          13         197        7746
Swap:          3181         203        2978

**Comment by jancborchardt** [comment] 2019-09-16 20:21
So is this a duplicate of https://github.com/nextcloud/maps/issues/128 and fixed by https://github.com/nextcloud/maps/pull/152 ?

**Closed** 2019-10-16 10:10 UTC
Labels: duplicate
