### ISSUE TITLE
Added photos all have NULL lat and lng in database

### ISSUE THREAD

**Issue by misterwrong** [nextcloud/maps#354] opened 2020-04-08 09:19 UTC
I have photos in two directories, one of which is shared with four other accounts. The other is not shared.

When manually scanning using
`su http -c ./occ maps:scan-photos`
from the root of my Nextcloud installation, the output shows it scans all photos from both directories, and does this in my accounts as well as the account with which I have shared these photos. The logs show only starting and stopping the scan job, but no errors or warnings. 

AJAX triggered background scans have the same result.

When looking into the database, the table "oc_maps_photos" contains only a fraction (38) of the photos scanned. For all of them the user_id column contains the name of one of the accounts I shared the photos with, the lat and lng columns are empty and the date_taken column is populated.

When redoing the scan, the database only contains fourteen photos, again without any lat or lng data.

All photos have EXIF GPS data. This is an example from one of the photo's:
```
$ identify -format '%[EXIF:*]' 20200401_105953.jpg | grep GPS
exif:GPSAltitude=0/1000
exif:GPSAltitudeRef=0
exif:GPSDateStamp=2020:04:01
exif:GPSInfo=735
exif:GPSLatitude=52/1, 24/1, 243035/10000
exif:GPSLatitudeRef=N
exif:GPSLongitude=4/1, 56/1, 3047/10000
exif:GPSLongitudeRef=E
exif:GPSProcessingMethod=65, 83, 67, 73, 73, 0, 0, 0, 67, 69, 76, 76, 73, 68, 0
exif:GPSTimeStamp=8/1, 59/1, 52/1
```
I would expect all photos to be added, for all accounts mentioned during scanning, and that their lat and lng data would be filled in.

**Comment by misterwrong** [comment] 2020-04-12 18:18
I added this problem here because this is where the "report a problem" button linked to.

**Comment by dasBuero** [comment] 2020-04-17 08:10
Same here. Just 113 photos with GPS data in `oc_maps_photos` out of 16k after scanning with `occ maps:scan-photos`.

@misterwrong Why did you closed this issue? Did you resolved it somehow?

**Comment by misterwrong** [comment] 2020-04-17 08:12
I closed it because nobody responded for a long time. But if I'm not the only one, lets reopen it.

**Comment by dasBuero** [comment] 2020-04-17 11:56
It seems I may have been a little fast. After about three hours the photos have turned up on my map and after a spot check, all photos seem to have been found with GPS data. Apparently the cron job of the maps plugin took longer than I expected.

Please excuse the rushed reporting here.

**Comment by misterwrong** [comment] 2020-04-17 12:43
My photos do not show up at all. @dasBuero do your photos have lat and lng data in your database?

**Comment by tacruc** [comment] 2020-04-17 13:16
It would be helpful to get some sample pictures, which end up with NULL NULL in the database. For all my images with geo tags stuff is working.

**Comment by misterwrong** [comment] 2020-04-17 13:26
![20191106_184118_HDR](https://user-images.githubusercontent.com/5786774/79573933-ad21be00-80bf-11ea-80c9-5a5543c06133.jpg)

This is a photo that does not show up, but should.

**Comment by tacruc** [comment] 2020-04-17 14:01
OK, the picture shows up on my development System and on my Production system.
Which type of cron are you using? https://docs.nextcloud.com/server/18/admin_manual/configuration_server/background_jobs_configuration.html?highlight=cron
I have no porblems with cron. I guess webcron works, too. If you use AJAX I guess you will have to reload the page quite often, but atleast once per picture.

**Comment by misterwrong** [comment] 2020-04-17 14:33
I was using AJAX but now I wrote a systemd trigger according to that page. It runs every 5 minutes and every time more pictures now show up, now including the one above. The database table contains 4386 references to images and 333 of them have lng and lat columns populated. I will wait what happens for now, but the manual scan job still has inconsistent and unusable results, so I suggest keeping this issue open until that is resolved.

**Comment by tacruc** [comment] 2020-04-17 14:40
Yes every picture is scaned in its own background job. We had huge problems, that corrupte pictures can crash the used php libs. As the images are all own jobs only the corrupted images is not shown. 

Multiple calls are needed as cron.php only processes jobs for 15 minutes. Otherwise to many multiple jobs might run at the same time.

Additionally it might take some time as every image has to be loaded. On my system it takes ~ 1-3 images per second.

**Closed by tacruc** 2020-04-17 14:40 UTC

**Comment by nicbou** [comment] 2020-06-04 18:58
As far as I'm concerned, this issue is not fixed.

1. On a fresh, unremarkable Nextcloud install, I get "media scan was not done yet. wait a few minutes/hours and reload this page to see your photos/tracks". I set up Nextcloud a month ago.
2. When I run the task manually, it blazes through my 945 photos in an instant.
3. No photos are returned. The API call returns an empty array.
4. The photos have GPS data. I verified myself.

**Comment by tacruc** [comment] 2020-06-04 22:12
Is the Cronjob executed correctly?

**Comment by nicbou** [comment] 2020-06-04 22:24
After some more research, the cron job was indeed to blame. I'm not sure about #1, but it was the cause of #3. I found the answer through a few different GitHub issues.

For future readers:

* The maps:scan-photos tasks only _queues_ the processing. It will not start until the scheduler executes the tasks.
* In the docker image, the default scheduler is AJAX. Each page load will process one task, or one picture. Reloading the page a few times will make more pictures appear on the map.

I do not know if all pictures will be processed yet. More testing is required. Thank you for your support.
