### ISSUE TITLE
Cannot create new users when Maps is enabled

### ISSUE THREAD

**Issue by bughunt3rz** [nextcloud/maps#179] opened 2019-10-04 12:14 UTC
Only when Maps app is enabled, creation of a new user fails. If I disable Maps, it works correctly.
I use a newly installed NC 17.0.0.9 on Debian 10, with encryption enabled.

[no app in context] Error: OCP\Files\NotPermittedException: Could not create folder at <<closure>>

 0. /var/www/nextcloud/lib/private/Files/Node/Root.php line 383
    OC\Files\Node\Folder->newFolder("/test/files")
 1. <<closure>>
    OC\Files\Node\Root->getUserFolder("test")
 2. /var/www/nextcloud/lib/private/Files/Node/LazyRoot.php line 64
    undefinedundefinedcall_user_func_array([OC\Files\Node\Root {},"getUserFolder"], ["test"])
 3. /var/www/nextcloud/lib/private/Files/Node/LazyRoot.php line 281
    OC\Files\Node\LazyRoot->__call("getUserFolder", ["test"])
 4. /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php line 90
    OC\Files\Node\LazyRoot->getUserFolder("test")
 5. /var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php line 103
    OCA\GroupFolders\Mount\MountProvider->getMountsForUser(OC\User\User {}, OC\Files\Storage\StorageFactory {})
 6. /var/www/nextcloud/lib/private/Files/Filesystem.php line 447
    OC\Files\Config\MountProviderCollection->addMountForUser(OC\User\User {}, OC\Files\Mount\Manager {})
 7. /var/www/nextcloud/lib/private/Files/Filesystem.php line 376
    OC\Files\Filesystem::initMountPoints("test")
 8. /var/www/nextcloud/lib/private/legacy/util.php line 309
    OC\Files\Filesystem::init("test", "/test/files")
 9. /var/www/nextcloud/apps/provisioning_api/lib/Controller/AUserData.php line 183
    OC_Util::setupFS("test")
10. /var/www/nextcloud/apps/provisioning_api/lib/Controller/AUserData.php line 131
    OCA\Provisioning_API\Controller\AUserData->fillStorageInfo("test")
11. /var/www/nextcloud/apps/provisioning_api/lib/Controller/UsersController.php line 384
    OCA\Provisioning_API\Controller\AUserData->getUserData("test")
12. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Provisioning_API\Controller\UsersController->getUser("test")
13. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Provisioning ... {}, "getUser")
14. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Provisioning ... {}, "getUser")
15. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Provisioni ... r", "getUser", OC\AppFramework\ ... {}, {userId: "test", ... "})
16. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({userId: "test", ... "})
17. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {userId: "test", ... "})
18. /var/www/nextcloud/ocs/v1.php line 82
    OC\Route\Router->match("/ocsapp/cloud/users/test")
19. /var/www/nextcloud/ocs/v2.php line 24
    undefinedundefinedrequire_once("/var/www/nextcloud/ocs/v1.php")

GET /ocs/v2.php/cloud/users/test

[log.txt](https://github.com/nextcloud/maps/files/3690428/log.txt)

**Comment by jancborchardt** [comment] 2019-10-09 19:32
I can’t reproduce this. It looks like it might be something else? @eneiluj @tacruc, maybe a core issue @rullzer?

**Comment by bughunt3rz** [comment] 2019-10-10 23:23
Yeah, you were right! I had a lot of plugins installed, so this was a real pain to find...
You can reproduce this by installing Maps AND Group Folders. If only one of the two is installed there is no problem. Should this be reported on core?

Also this is the correct log. for some reason the first one was incomplete
[right-log.txt](https://github.com/nextcloud/maps/files/3714933/right-log.txt)

**Comment by jancborchardt** [comment] 2019-10-11 11:22
cc @icewind1991 @juliushaertl because of the groupfolders conflict then. Any idea?

@bughunt3rz thanks for doing the digging! :)

**Comment by abrain** [comment] 2020-01-11 19:44
Having both Maps and Group Folders enabled, this does not happen to me when creating new users. @bughunt3rz Do you still face this issue?

**Versions:**
Nextcloud: 17.0.2
Maps: 0.1.2
Group Folders: 5.0.5

Encryption is not enabled.

**Comment by abrain** [comment] 2020-01-11 19:56
Oh, I'm sorry. It does indeed happen to me as well 😆 

The thing is that the user gets created, and everything seems fine. The creation fails silently.

As you mentioned, the user folder is not created, and also no welcome email is sent. Resending the welcome email also fails silently.

**Comment by zentavr** [comment] 2020-01-14 10:53
I hadn't *Group Folders* installed, but had only *Maps 0.1.2*. When I disabled the plugin - user was able to log in.

**Comment by jancborchardt** [comment] 2020-01-15 00:14
cc @juliushaertl for groupfolders then – any idea what could cause this conflict? :)

**Comment by tacruc** [comment] 2020-01-15 12:29
I think it is an duplacte of  #138 and should be fixed with  #139.
@bughunt3rz can you check if the master is still producing the error.

**Closed** 2020-01-16 00:23 UTC
Labels: bug, duplicate, question
