### ISSUE TITLE
Division by zero at /var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php#413

### ISSUE THREAD

**Issue by cagial** [nextcloud/maps#645] opened 2021-08-14 08:22 UTC
{"reqId":"nArEhugwWE2sGg728epV","level":3,"time":"2021-08-07T18:20:03+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"Division by zero at /var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php#413","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php","line":413,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Division by zero","/var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php",413,{"0":"And 6 more entries, set log level to debug to see all entries","file":{"__class__":"OC\\Files\\Node\\File"},"path":"/media/nextcloud/data/XXX/files/Fotos/XXX/XXX.jpg","has_info":false,"exif":{"0":"And 56 more entries, set log level to debug to see all entries","FileName":"XXX.jpg","FileDateTime":1628359859,"FileSize":3031758,"FileType":2,"MimeType":"image/jpeg"},"LatM":1}]},{"file":"/var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php","line":264,"function":"getExif","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"}]},{"file":"/var/www/nextcloud/apps/maps/lib/BackgroundJob/AddPhotoJob.php","line":56,"function":"addPhotoNow","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},"XXX"]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\Maps\\BackgroundJob\\AddPhotoJob","type":"->","args":[{"photoId":12345,"userId":"XXX"}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":48,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"--","version":"21.0.3.1","id":"61177c3204374"}

**Comment by spicemint** [comment] 2021-08-21 07:15
also getting divisions by zero when cron job runs in conjunction with maps, working on nextcloud 22.1.0, Linux 5.13.9-arch1-1 x86_64; php 8.0.9; mariadb 10.6.4; nginx 1.20.1-1; no external storage being used,

**Comment by kovge** [comment] 2021-09-01 19:10
I seen the same issue.
This pull request could be a solution for it: https://github.com/nextcloud/maps/pull/586

**Comment by umgfoin** [comment] 2022-01-21 08:15
Duplicate of #655

**Closed** 2022-02-20 21:52 UTC
