### ISSUE TITLE
Clicking on one contact on Chromium-based Browsers on Android opens the popup twice

### ISSUE THREAD

**Issue by szaimen** [nextcloud/maps#130] opened 2019-09-05 15:06 UTC
When I click on contacts on Chromium-based Browsers on Android, the popup with further informations about the contact opens twice. I think that shouldn't be the case here.
Thank you!
Here are two screenshots:
When clicking on the contact fist:
![photo5442855309845572448](https://user-images.githubusercontent.com/42591237/64358464-cc734b80-d006-11e9-8a48-bcd7533daba4.jpg)
After closing the first popup:
![photo5442913704220929062](https://user-images.githubusercontent.com/42591237/64358504-de54ee80-d006-11e9-8875-ef5fd3996035.jpg)
Maybe it is related to https://github.com/nextcloud/maps/issues/133?

**Comment by jancborchardt** [comment] 2019-09-05 21:09
Closing as duplicate of https://github.com/nextcloud/maps/issues/133

**Closed by jancborchardt** 2019-09-05 21:09 UTC
Labels: bug, feature: 👥 contacts
