### ISSUE TITLE
Error: Required parameter $begin / $end follows optional parameter $deviceIdList / $categoryList

### ISSUE THREAD

**Issue by TheColin21** [nextcloud/maps#665] opened 2021-11-30 22:32 UTC
After upgrading to Nextcloud 23 I get those errors a lot: 

```
Error: Required parameter $end follows optional parameter $deviceIdList at /var/www/vhosts/domain.tld/httpdocs/apps/maps/lib/Controller/DevicesController.php#175
/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 571:

OC\Log\ErrorHandler::onError()

/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 571:

include()

/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 428:

Composer\Autoload\includeFile()

<<closure>>

Composer\Autoload\ClassLoader->loadClass()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 112:

ReflectionClass->__construct()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:

OC\AppFramework\Utility\SimpleContainer->resolve()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 463:

OC\AppFramework\Utility\SimpleContainer->query()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 435:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/App.php - line 144:

OC\AppFramework\DependencyInjection\DIContainer->query()

/var/www/vhosts/domain.tld/httpdocs/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/vhosts/domain.tld/httpdocs/lib/base.php - line 1006:

OC\Route\Router->match()

/var/www/vhosts/domain.tld/httpdocs/index.php - line 36:

OC::handleRequest()
```

```
Error: Required parameter $begin follows optional parameter $deviceIdList at /var/www/vhosts/domain.tld/httpdocs/apps/maps/lib/Controller/DevicesController.php#175
/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 571:

OC\Log\ErrorHandler::onError()

/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 571:

include()

/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 428:

Composer\Autoload\includeFile()

<<closure>>

Composer\Autoload\ClassLoader->loadClass()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 112:

ReflectionClass->__construct()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:

OC\AppFramework\Utility\SimpleContainer->resolve()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 463:

OC\AppFramework\Utility\SimpleContainer->query()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 435:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/App.php - line 144:

OC\AppFramework\DependencyInjection\DIContainer->query()

/var/www/vhosts/domain.tld/httpdocs/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/vhosts/domain.tld/httpdocs/lib/base.php - line 1006:

OC\Route\Router->match()

/var/www/vhosts/domain.tld/httpdocs/index.php - line 36:

OC::handleRequest()
```

```
Error: Required parameter $end follows optional parameter $categoryList at /var/www/vhosts/domain.tld/httpdocs/apps/maps/lib/Controller/FavoritesController.php#216
/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 571:

OC\Log\ErrorHandler::onError()

/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 571:

include()

/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 428:

Composer\Autoload\includeFile()

<<closure>>

Composer\Autoload\ClassLoader->loadClass()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 112:

ReflectionClass->__construct()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:

OC\AppFramework\Utility\SimpleContainer->resolve()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 463:

OC\AppFramework\Utility\SimpleContainer->query()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 435:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/App.php - line 144:

OC\AppFramework\DependencyInjection\DIContainer->query()

/var/www/vhosts/domain.tld/httpdocs/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/vhosts/domain.tld/httpdocs/lib/base.php - line 1006:

OC\Route\Router->match()

/var/www/vhosts/domain.tld/httpdocs/index.php - line 36:

OC::handleRequest()
```

```
	Error: Required parameter $begin follows optional parameter $categoryList at /var/www/vhosts/domain.tld/httpdocs/apps/maps/lib/Controller/FavoritesController.php#216
/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 571:

OC\Log\ErrorHandler::onError()

/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 571:

include()

/var/www/vhosts/domain.tld/httpdocs/lib/composer/composer/ClassLoader.php - line 428:

Composer\Autoload\includeFile()

<<closure>>

Composer\Autoload\ClassLoader->loadClass()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 112:

ReflectionClass->__construct()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:

OC\AppFramework\Utility\SimpleContainer->resolve()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 463:

OC\AppFramework\Utility\SimpleContainer->query()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 435:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/var/www/vhosts/domain.tld/httpdocs/lib/private/AppFramework/App.php - line 144:

OC\AppFramework\DependencyInjection\DIContainer->query()

/var/www/vhosts/domain.tld/httpdocs/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/vhosts/domain.tld/httpdocs/lib/base.php - line 1006:

OC\Route\Router->match()

/var/www/vhosts/domain.tld/httpdocs/index.php - line 36:

OC::handleRequest()
```

The issue shouldn't be too hard to fix by... changing the order of arguments.

**Comment by schanceee** [comment] 2021-12-26 11:50
I have tried to scan my photos using the command: 
first: `sudo -u www-data php occ maps:scan-photos `
and then: `sudo -u www-data php occ maps:scan-photos userid`

Each time, the nextcloud logs show the following errors: 
`Required parameter $end follows optional parameter $deviceIdList at /var/www/nextcloud/apps/maps/lib/Controller/DevicesController.php#175`
`Required parameter $end follows optional parameter $categoryList at /var/www/nextcloud/apps/maps/lib/Controller/FavoritesController.php#216`

I have a setup with 3 external storages folders from my qnap nas. From what I read in other issues, this seems to be the problem. However I cannot figure out how to solve it.

Do you know what I should do to fix it?

**Comment by doc75** [comment] 2022-01-05 21:31
I got the same error message just after upgrading to Maps 0.1.10 (I am on Nextcloud 22.2.3).

```
Required parameter $end follows optional parameter $categoryList at /var/www/html/custom_apps/maps/lib/Controller/FavoritesController.php#216
Required parameter $end follows optional parameter $deviceIdList at /var/www/html/custom_apps/maps/lib/Controller/DevicesController.php#175
```

**Comment by doc75** [comment] 2022-01-15 17:41
I just checked and the error is also raised with Maps 0.1.9 (still Nextcloud 22.2.3 official docker image)

**Comment by tacruc** [comment] 2022-06-16 10:51
Could you check if v0.2.0-1-nightly solves the Issue.
It can be installed by
occ app:install maps --allow-unstable
or updated
occ app:update maps --allow-unstable

**Comment by andyxheli** [comment] 2022-07-11 19:38
Same issue NC 24.0.3 RC2 Map app 	0.1.10

**Comment by tacruc** [comment] 2023-03-03 23:22
I will close this as it was not confirmed for v0.2.0, feel free to reopen if it occurs in v0.2.5 nightly

**Closed by tacruc** 2023-03-03 23:22 UTC
