### ISSUE TITLE
Geo property of a contact is ignored by Maps

### ISSUE THREAD

**Issue by tdoerschel** [nextcloud/maps#634] opened 2021-07-06 06:52 UTC
Steps to reproduce:
1. create a new contact
2. add coordinates to the geo property field of this contact
3. go to Maps app:  the contact is not shown

Expected behaviour:
Contacts with geo coordinates should be displayed on map (not only adress fields. Often the locations have no adress)

Setups tested:
I tested it with 2 setups:
Nextcloud server 20.0.11
contacts 3.5.1
maps 0.1.8
PHP 7.3.28
mysql 5.7.34

and
Nextcloud server 21.0.3
contacts 3.5.1
maps 0.1.8
PHP 7.4.20
pqsql 7.50

See also #401 

My company is willing to pay for this bug to be fixed. Let me know if you accept bountysource or if you have other preferences.

Cheers,
Torsten

**Comment by tdoerschel** [comment] 2021-10-11 07:44
I checked on an old instance with server  20.0.13:
new contacts with adresses are put on maps, but still no geo coordinates (even after fixing above error)

**Comment by satyamkapoor** [comment] 2022-03-29 23:24
Hey, how did you fix the above error?

**Comment by tacruc** [comment] 2022-03-30 11:20
Could you check if  #709 solves your problem?

**Comment by satyamkapoor** [comment] 2022-04-13 05:39
> Could you check if  #709 solves your problem?

Unfortunately it didn't work. 

Upon debugging I found some geo co ordinates causing the issue. It's more of a Contacts issue when using a mix or thunderbird iOS. Managed to get it working now. 

Thank you!

**Comment by tacruc** [comment] 2022-04-13 06:49
Can you Providence some sample data.

**Comment by satyamkapoor** [comment] 2022-04-13 06:56
Ok I solved it in a very bad way. Started sending the output to a telegram chat. Initially it was an Array. Which it was complaining of. When i printed index 1 of the array it got me 90. Then I tried checking mariadb table with the associated id and it was going no where. At last I downloaded my contact list from nextcloud UI. Searched for 90 which was a Geo attribute. Deleted the line and imported it back. :( This was the only line with GEO attribute. 

![image](https://user-images.githubusercontent.com/6293731/163117905-9a33ae86-74d8-40dd-ba3b-8dc55c3bad96.png)

Removing `GEO;VALUE=FLOAT:90` solved it for me :(

**Comment by tacruc** [comment] 2022-04-13 07:31
OK I don't get it.
What are you typing into the Geo field to reproduce this issue?

**Comment by satyamkapoor** [comment] 2022-04-13 07:43
Apologies for being unclear. I think there were too many tickets on this issue and I perhaps wrongly added my comment here. I just wanted to solve this issue and described above the thing which helped me byepass for the moment. But this just confirms the issue is a correct one and related to GEO field. 

Feel bad for spamming by stupid comments here. Please ignore.

**Comment by tacruc** [comment] 2023-03-04 00:02
Should be fixed in v0.2.5 feel free to reopen if I'm wrong.

**Closed by tacruc** 2023-03-04 00:02 UTC
