### ISSUE TITLE
non well formed numeric value / division by zero

### ISSUE THREAD

**Issue by langfingaz** [nextcloud/maps#375] opened 2020-05-05 16:14 UTC
Hey,
I have multiple error messages of these two types in my Nextcloud log. Any ideas, what could cause them?
I am running Nextcloud 18.0.4 with maps 0.1.6.

```
{
  "reqId": "jI4eyypgUj47UsPzKtb4",
  "level": 3,
  "time": "2020-05-05T15:21:53+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "PHP",
  "method": "",
  "url": "--",
  "message": "Division by zero at /data/nextcloud/apps/maps/lib/Service/PhotofilesService.php#407",
  "userAgent": "--",
  "version": "18.0.4.2",
  "id": "5eb18edfbd7fe"
}
```

```
{
  "reqId": "3vktxvOizVXjGScETzm2",
  "level": 3,
  "time": "2020-05-05T15:38:46+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "PHP",
  "method": "",
  "url": "--",
  "message": "A non well formed numeric value encountered at /data/nextcloud/apps/maps/vendor/lsolesen/pel/src/PelIfd.php#611",
  "userAgent": "--",
  "version": "18.0.4.2",
  "id": "5eb18def15e3b"
}
```

If I can help help you in any way by providing further information, please let me now!

**Comment by tacruc** [comment] 2020-05-05 16:17
Yeah pleas check if it is a duplicate of  #245?

**Comment by langfingaz** [comment] 2020-05-05 16:21
> Yeah pleas check if it is a duplicate of #245?

Thanks I'll check that. I've overseen that similar issue.

**Closed** 2020-06-03 18:10 UTC
