### ISSUE TITLE
Nextcloud cron job crashes when Maps is installed

### ISSUE THREAD

**Issue by sqhn** [nextcloud/maps#337] opened 2020-03-18 08:29 UTC
Hello

I have the latest version of Nextcloud freshly installed (18.0.2) and maps. I set up the background tasks with a cron task calling cron.php. It worked correctly until and I installed maps package. I also use group folders, thus it might be related to this issue : [Images and tracks in group folders are not scanned · Issue #123 · nextcloud/maps](https://github.com/nextcloud/maps/issues/123) but in my case, the whole nextcloud background job fails, impacting other apps.

Here is the error in the log:

Error: Call to a member function getUID() on null
    /var/www/nextcloud/apps/maps/lib/BackgroundJob/UpdatePhotoByFileJob.php - line 56:
    OCA\Maps\Service\PhotofilesService->updateByFileNow("*** sensiti ... *")
    /var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 79:
    OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run({ fileId: 75 ... "})
    /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php - line 48:
    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
    /var/www/nextcloud/cron.php - line 125:
    OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

Thanks

**Comment by tacruc** [comment] 2020-04-17 14:35
Duplicate of #247

**Closed by tacruc** 2020-04-17 14:35 UTC
