### ISSUE TITLE
Nextcloud 24: Cron fails in rootless mode due to maps

### ISSUE THREAD

**Issue by Moltey** [nextcloud/maps#734] opened 2022-05-09 00:48 UTC
I am running nextcloud 24 in rootless podman in two containers:
* app container
* cron container

Both containers are executed with "--user 1008". It worked fine until I updgraded to nextcloud 24. The cronjob is failing entirely due to maps:

``` 
$ podman exec --user 1008 -t nxtcld-ml-cron php -f cron.php
TypeError: Unsupported operand types: int * string in /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php:447                                             
Stack trace:                                            
#0 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php(368): lsolesen\pel\PelIfd->loadSingleValue(Object(lsolesen\pel\PelDataWindow), 10, 31, 0)         
#1 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelTiff.php(159): lsolesen\pel\PelIfd->load(Object(lsolesen\pel\PelDataWindow), 10)                          
#2 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelExif.php(108): lsolesen\pel\PelTiff->load(Object(lsolesen\pel\PelDataWindow))                              
#3 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(216): lsolesen\pel\PelExif->load(Object(lsolesen\pel\PelDataWindow))                              
#4 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(126): lsolesen\pel\PelJpeg->load(Object(lsolesen\pel\PelDataWindow))                              
#5 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(442): lsolesen\pel\PelJpeg->__construct(Object(lsolesen\pel\PelDataWindow))                         
#6 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(384): OCA\Maps\Service\PhotofilesService->getExifPelBackup(Object(OC\Files\Node\File))              
#7 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(264): OCA\Maps\Service\PhotofilesService->getExif(Object(OC\Files\Node\File))                       
#8 /var/www/html/custom_apps/maps/lib/BackgroundJob/AddPhotoJob.php(56): OCA\Maps\Service\PhotofilesService->addPhotoNow(Object(OC\Files\Node\File), 'moltey')           
#9 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\Maps\BackgroundJob\AddPhotoJob->run(Array)           
#10 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))                          
#11 /var/www/html/cron.php(151): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))                                                 
#12 {main}
```

Any idea what might cause this issue?

I start the cron container via:
``` bash
podman run -d \
  --name=nextcloud-cron \
  --pod=nextcloud \
  --restart unless-stopped \
  --runtime crun \
  --user 1008:1008 \
  -v ~/nc/html:/var/www/html:z \
  -v ~/nc/data:/var/www/data:z \
  --cap-add=CAP_NET_BIND_SERVICE \
  --cap-add=CAP_SETGID \
  --cap-add=CAP_SETUID \
  --entrypoint=/cron.sh \
  docker.io/library/nextcloud:fpm-alpine
```

**Comment by tacruc** [comment] 2022-05-09 06:27
How is this not a duplicate of #640?

**Closed by tacruc** 2022-05-09 06:27 UTC
