### ISSUE TITLE
Cron Job for Nextcloud stops functioning when enabling maps

### ISSUE THREAD

**Issue by 4onUser** [nextcloud/maps#291] opened 2020-02-10 18:20 UTC
The recent addition of using an automated background job for scanning things for map locations seems to be the source of my cron job for Nextcloud failing to function any longer.  Once Maps is disabled, the cron job resumes functionality, enabled it breaks again.  This is on a Synology system so I'm not sure whether this is a system issue or a programming issue.  I'm also reticent to believe that automating a system wide scan for this is an appropriate action rather than being able to choose what gets scanned and mapped thus I'm not pleased with this addition for multiple reasons.

These error messages occur to help troubleshooting:
[PHP] Error: Undefined property: OCA\Maps\BackgroundJob\UpdatePhotoByFileJob::$root at /volume1/web/nextcloud/apps/maps/lib/BackgroundJob/UpdatePhotoByFileJob.php#43

[cron] Error: Error: Call to a member function getUserFolder() on null at <<closure>>

0. /volume1/web/nextcloud/lib/public/BackgroundJob/Job.php line 77
   OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run({fileId: 617147,userId: ""})
1. /volume1/web/nextcloud/lib/public/BackgroundJob/QueuedJob.php line 46
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
2. /volume1/web/nextcloud/cron.php line 124
   OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
at 2020-02-10T16:30:01+00:00

**Comment by OlavStornes** [comment] 2020-02-11 14:36
The issue is fixed at #247, and will (by my understanding) be rolled out in version 0.1.5

**Comment by Silberschleier** [comment] 2020-02-14 12:30
When can we expect the release of 0.1.5?

**Comment by tacruc** [comment] 2020-02-14 13:46
When  #254 is merged.

**Comment by simeneriks1** [comment] 2020-02-14 15:52
I hope to see this update rolled out as soon as possible, as my cronjobs are not working at the moment. When you provide the community with broken updates like this, i would love to see priority given to it asap. I am in advance, sorry if I interpret this wrongly. This merge request has been open for a month at this time.
I do respect the work you do, but this should not take so long? I am also reliant on the maps so I can't easily disable it. I am also not trying to put someone under the flame, but I just want it being followed up on whenever possible.

Please let me know if i can be of any help providing you with log entries or so.
Thank you very much for understanding, and I wish you good luck.
@jancborchardt for your information, as you are listed as PR approver on #254

**Comment by gabrielklein** [comment] 2020-02-17 12:10
I have "disabled" maps and it works perfectly. I'll reenable it when version 0.1.5 is release. Special thank for all the developers for this great plugin even if it doesn't work for now.

**Closed** 2020-02-17 21:14 UTC

**Comment by gabrielklein** [comment] 2020-02-17 21:15
Thank you :) 0.1.5 fix the issue for me!
(The cron takes hours... but it's probably another problem.)

**Comment by tacruc** [comment] 2020-02-17 21:19
> (The cron takes hours... but it's probably another problem.)

Well I guess a second per picture, is reasonable. Which makes ~3 hours per 10000 pictures.
