### ISSUE TITLE
Error Doctrine\DBAL\Exception\DriverException when trying to display track

### ISSUE THREAD

**Issue by chullski** [nextcloud/maps#283] opened 2020-02-01 13:22 UTC
Hey all,

I'm getting the following error when I try to display an .gpx track file on the map. The file ist 26mb big.
`[index] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_maps_tracks` SET `metadata` = ?, `etag` = ? WHERE `id` = ?' with params ["{\"lat\":52.834936, \"lng\":5.693207, \"name\": \"191007_Ijsselmeer_Nordseerunde_Tracks.gpx\", \"distance\": 293487.910, \"duration\": 277617, \"begin\": 1570094299, \"end\": 1570371916, \"posel\": 1468.00, \"negel\": 1189.00, \"minel\": 23.00, \"maxel\": 57.00, \"maxspd\": 58.20, \"avgspd\": 3.81, \"movtime\": 99916, \"stptime\": 8451, \"movavgspd\": 10.57, \"n\": 52.99150200, \"s\": 52.36883400, \"e\": 5.70715600, \"w\": 4.53417400, \"trnl\": [\"Lemmer - Amsterdam\",\"Amsterdam - Ijmuiden\",\"Ijmuiden - Hindeloopen\",\"Hindeloopen - Lemmer\"], \"lnkurl\": \"\", \"lnktxt\": \"\", \"movpace\": 5.67}", "f34ef273321fda062dbd90f4dd24d09f", 6]:

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'metadata' at row 1 at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... 1", Doctrine\DBAL\Dr ... ]})
 1. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... 1")
 2. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1063
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "UPDATE `oc_maps ... ?", {1: "{\"lat\":52 ... 6})
 3. /var/www/html/lib/private/DB/Connection.php line 220
    Doctrine\DBAL\Connection->executeUpdate("UPDATE `oc_maps ... ?", ["{\"lat\":52.83 ... 6], [2,2,1])
 4. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 203
    OC\DB\Connection->executeUpdate("UPDATE `oc_maps ... 4", {dcValue1: "6",d ... 6}, {dcValue1: 1,dcV ... 1})
 5. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 215
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/html/custom_apps/maps/lib/Service/TracksService.php line 299
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/html/custom_apps/maps/lib/Controller/TracksController.php line 121
    OCA\Maps\Service\TracksService->editTrackInDB(6, null, "{\"lat\":52.834 ... }", "f34ef273321fda062dbd90f4dd24d09f")
 8. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Maps\Controller\TracksController->getTrackFileContent("6")
 9. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Maps\Controller\TracksController {}, "getTrackFileContent")
10. /var/www/html/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Maps\Controller\TracksController {}, "getTrackFileContent")
11. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("TracksController", "getTrackFileContent", OC\AppFramework\ ... {}, {id: "6",_route: ... "})
12. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({id: "6",_route: ... "})
13. /var/www/html/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {id: "6",_route: ... "})
14. /var/www/html/lib/base.php line 1008
    OC\Route\Router->match("/apps/maps/tracks/6")
15. /var/www/html/index.php line 38
    OC::handleRequest()

GET /apps/maps/tracks/6
from 172.31.0.1 by julian at 2020-02-01T13:13:27+00:00`

**Comment by JohnWalkerx** [comment] 2020-08-09 13:17
Duplicate of #377 
There you can find also a [solution](https://github.com/nextcloud/maps/issues/377#issuecomment-629701944).

**Closed** 2023-03-04 00:21 UTC
