### ISSUE TITLE
Cron Job fails when Maps is activated

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/maps#272] opened 2020-01-23 10:04 UTC
Hello, since the latest Update the Cronjob fails in NC. 

Systeminfos:

https://cloud.larsmueller.net/s/QyqMByDCx7XiLoH

Logentrys:

`Error: Call to a member function getUserFolder() on null
/var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 79:
OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run({ fileId: 25 ... "})
/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php - line 48:
OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
/var/www/nextcloud/cron.php - line 125:
OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})`

`Undefined property: OCA\Maps\BackgroundJob\UpdatePhotoByFileJob::$root at /var/www/nextcloud/apps/maps/lib/BackgroundJob/UpdatePhotoByFileJob.php#43`

**Comment by tacruc** [comment] 2020-01-23 10:07
Fixed in  #251
Duplicate of #247, Isn't it your issue @Happyfeet01  are you reading the errors your posting or are you just copy pasting everything into a new issue?

**Comment by Happyfeet01** [comment] 2020-01-23 10:08
Yes, sorry for duplicate content 🙈

**Closed by tacruc** 2020-01-23 10:08 UTC
