### ISSUE TITLE
Make large thumbnails accessible on mobile devices

### ISSUE THREAD

**Issue by stephanhoennekes** [nextcloud/maps#141] opened 2019-09-08 10:18 UTC
If an image on the map is clicked on a mobile device, the image will be opened in the gallery app immediately. Like this it‘s not possible to have a quick view on the larger version of the image from within the maps app.

Would be great if on mobile the first click would open the larger view and the second click (on the large thumbnail) would open the gallery app.

Tested on iOS 12.4 in Safari

**Comment by tacruc** [comment] 2019-09-08 10:26
Related to #93

**Comment by jancborchardt** [comment] 2019-09-10 13:55
I’d say we can close this as duplicate of #93 because when we open the viewer on click, it’s really easy to close again.

**Closed by jancborchardt** 2019-09-10 13:55 UTC
