### ISSUE TITLE
How is "your devices" supposed to work?

### ISSUE THREAD

**Issue by mnlipp** [nextcloud/maps#205] opened 2019-10-28 09:03 UTC
Great app, great fun! I clicked around and found out about almost everything (I think) but how is "Your devices" supposed to work? It suggests some tracking feature, but how do I add a device and how is its position updated?

**Comment by jancborchardt** [comment] 2019-10-29 15:09
This is a duplicate of https://github.com/nextcloud/maps/issues/113 :) let’s continue there.

**Closed by jancborchardt** 2019-10-29 15:09 UTC
